airports = [
    'Akron–Canton Airport',
    'Akron Fulton International Airport',
    'Albany International Airport',
    'Albuquerque International Sunport',
    'Ted Stevens Anchorage International Airport',
    'Appleton International Airport',
    'Hartsfield-Jackson Atlanta International Airport',
    'Atlantic City International Airport',
    'Austin-Bergstrom International Airport',
    'Baltimore-Washington International Thurgood Marshall Airport',
    'Bangor International Airport',
    'Birmingham-Shuttlesworth International Airport',
    'Logan International Airport',
    'Buffalo Niagara International Airport',
    'Charlotte/Douglas International Airport',
    'Charleston International Airport',
    'Chicago Midway International Airport',
    'Chicago Rockford International Airport',
    'O\'Hare International Airport',
    'Cincinnati/Northern Kentucky International Airport',
    'Cleveland Hopkins International Airport',
    'Port Columbus International Airport',
    'Rickenbacker International Airport',
    'Dallas/Fort Worth International Airport',
    'Dayton International Airport',
    'Denver International Airport',
    'Des Moines International Airport',
    'Detroit Metropolitan Wayne County Airport',
    'Fairbanks International Airport',
    'Fort Lauderdale-Hollywood International Airport',
    'Southwest Florida International Airport',
    'Fresno Yosemite International Airport',
    'Bradley International Airport',
    'Hilo International Airport',
    'Honolulu International Airport',
    'George Bush Intercontinental Airport',
    'William P. Hobby Airport',
    'Huntsville International Airport',
    'Indianapolis International Airport',
    'Jacksonville International Airport',
    'Juneau International Airport',
    'Kansas City International Airport',
    'Ketchikan International Airport',
    'Key West International Airport',
    'Kona International Airport',
    'Capital Region International Airport',
    'McCarran International Airport',
    'Los Angeles International Airport',
    'Louisville International Airport',
    'Melbourne International Airport',
]