# Generated by Django 2.0.4 on 2018-04-22 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwApp', '0002_auto_20180422_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imie')),
                ('surname', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_to_flight', to='wwwApp.Flight')),
            ],
        ),
    ]
