# Generated by Django 2.0.4 on 2018-05-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwApp', '0003_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain_name', models.CharField(max_length=50, verbose_name='Imie kapitana')),
                ('captain_surname', models.CharField(max_length=50, verbose_name='Nazwisko kapitana')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wwwApp.Crew', verbose_name='Załoga'),
        ),
    ]
