# Generated by Django 2.0.4 on 2018-05-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwApp', '0004_auto_20180516_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='crew',
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
    ]
